#I collaborated with Rebecca LaRochelle and the subreddit for portions of this assignment.
source("http://jonsmitchell.com/code/reformatData07.R")
source("http://jonsmitchell.com/code/simFxn.R")
plot(1, 1, type="n", xlim=c(1998, 2013), ylim=c(0, 1))
s <- apply(overallFreq, 2, function(x) lines(overallFreq[,1], x, col=rgb(0, 0, 0, 0.01)))
rescaleFreq <- apply(overallFreq[,3:ncol(overallFreq)], 2, function(x) x-x[1])
plot(1, 1, type="n", xlim=c(1998, 2013), ylim=c(-0.25, 0.25))
s <- apply(rescaleFreq, 2, function(x) lines(overallFreq[,1], x, col=rgb(0, 0, 0, 0.01)))
dYear <- c()
dAlleles <- c()
for(i in 3:ncol(overallFreq)) {
  dYear <- c(dYear, overallFreq[,1])
  Vec <- overallFreq[,i]
  Init <- overallFreq[1,i]
  dAlleles <- c(dAlleles, Vec-Init)
}
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=100, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
plot(alleleFreqs$d_freq, alleleFreqs$d_imm, xlim=c(-0.15, 0.15), xlab="overall freq. change", ylab="freq. change in subset")
points(alleleFreqs$d_freq, alleleFreqs$d_birth, col='blue')
points(alleleFreqs$d_freq, alleleFreqs$d_surv, col='red')
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=100, h=5, s=5, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
addFit(nruns=50, n=100, h=0.5, s=0.5, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
addFit(nruns=50, n=100, h=0.1, s=0.1, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=100, h=0.1, s=-0.1, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=50, h=0, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=500, h=0, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=200, h=0, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=200, h=0.1, s=0.1, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=200, h=0.1, s=0.1, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=200, h=1, s=0.1, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=200, h=1, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=175, h=1, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=200, h=2, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=200, h=4, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=200, h=50, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=200, h=100, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=200, h=200, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=200, h=10000, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=150, h=50, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=250, h=50, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=200, h=100000, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=150, h=50, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=200, h=50, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
smoothScatter(dYear, dAlleles, colramp=Pal, nbin=100, xlab="year", ylab="change in allele freq. since 1998")
addFit(nruns=50, n=185, h=50, s=0, ngens=18, startT=1997, simCol="gray40", rescale=TRUE)
#The combination of n, h, and s that produces changes comparable to what is seen in the scrub jay population is n=185, h=50, s=0. 
#Changing 'h' seemed to do nothing, and changing 's' pitched the lines up (if s was positive) or down (if s was negative). Since the scrub jay allele freq. data seemed to diverge from 0.0 positively and negatively at an equal rate, it made sense to me to leave s at 0.
#For 'n', I chose 185 because of all the values I tested, it mirrored the allele freq. data the closest in my opinion.
#When set to n=185, h=50, s=0, the lines produced seemed to follow the allele freq. data most consistently, while still allowing for a few outliers, same as the allele freq. data.